version: "3.9"
services:
  next:
    command: sh -c "yarn build && yarn start -p 8080"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/home/node/app"
      - "/home/node/app/node_modules"
    ports:
      - "80:8080"
